version: "3"
services:
  engecopi_transferencia:
    image: tomcat:8
    container_name: eng_transferencia
    ports:
      - "8018:8080"
    environment:
      TZ: "America/Fortaleza"
      EBEAN_PROPS: /etc/ebean.properties
      LANG: 'pt_BR.UTF-8'
      LANGUAGE: 'pt_BR:pt'
      LC_ALL: 'pt_BR.UTF-8'
    volumes:
      - ./build/libs/producao.war:/usr/local/tomcat/webapps/transferenciaBancaria.war
      - ./ebean.properties:/etc/ebean.properties
    restart: always
    networks:
      rede_transferencia:
        ipv4_address: 172.118.1.1
networks:
  rede_transferencia:
    ipam:
      driver: default
      config:
        - subnet: 172.118.0.0/16
